/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      fontFamily: {
        jakarta: ['"Plus Jakarta Sans"', 'sans-serif'],
        sans: ['Inter', 'ui-sans-serif', 'system-ui', 'sans-serif'],
      },
      colors: {
        // Material Design 3 color system — exacto del diseño Stitch
        'primary':                    '#ab3500',
        'on-primary':                 '#ffffff',
        'primary-container':          '#ff6b35',
        'on-primary-container':       '#5f1900',
        'primary-fixed':              '#ffdbd0',
        'primary-fixed-dim':          '#ffb59d',
        'on-primary-fixed':           '#390c00',
        'on-primary-fixed-variant':   '#832600',
        'secondary':                  '#384dd0',
        'on-secondary':               '#ffffff',
        'secondary-container':        '#5367ea',
        'on-secondary-container':     '#fffbff',
        'secondary-fixed':            '#dfe0ff',
        'secondary-fixed-dim':        '#bbc3ff',
        'on-secondary-fixed':         '#000e5f',
        'on-secondary-fixed-variant': '#1c34ba',
        'tertiary':                   '#3b6a00',
        'on-tertiary':                '#ffffff',
        'tertiary-container':         '#62ac00',
        'on-tertiary-container':      '#1d3900',
        'tertiary-fixed':             '#9ffa41',
        'tertiary-fixed-dim':         '#85dd21',
        'on-tertiary-fixed':          '#0e2000',
        'on-tertiary-fixed-variant':  '#2b5000',
        'background':                 '#f9f9fc',
        'on-background':              '#1a1c1e',
        'surface':                    '#f9f9fc',
        'on-surface':                 '#1a1c1e',
        'surface-variant':            '#e2e2e5',
        'on-surface-variant':         '#594139',
        'surface-container':          '#eeeef0',
        'surface-container-low':      '#f3f3f6',
        'surface-container-high':     '#e8e8ea',
        'surface-container-lowest':   '#ffffff',
        'surface-container-highest':  '#e2e2e5',
        'surface-tint':               '#ab3500',
        'surface-dim':                '#dadadc',
        'surface-bright':             '#f9f9fc',
        'outline':                    '#8d7168',
        'outline-variant':            '#e1bfb5',
        'error':                      '#ba1a1a',
        'on-error':                   '#ffffff',
        'error-container':            '#ffdad6',
        'on-error-container':         '#93000a',
        'inverse-primary':            '#ffb59d',
        'inverse-surface':            '#2f3133',
        'inverse-on-surface':         '#f0f0f3',
      },
      boxShadow: {
        'ambient':       '0 4px 20px 0 rgba(0,0,0,0.06)',
        'ambient-hover': '0 8px 28px 0 rgba(0,0,0,0.13)',
      },
      fontSize: {
        'display-lg':        ['3rem',    { lineHeight: '3.5rem',   letterSpacing: '-0.02em', fontWeight: '800' }],
        'display-lg-mobile': ['2.25rem', { lineHeight: '2.625rem', letterSpacing: '-0.02em', fontWeight: '800' }],
        'headline-md':       ['1.5rem',  { lineHeight: '2rem',     fontWeight: '700' }],
        'body-lg':           ['1.125rem',{ lineHeight: '1.75rem' }],
        'label-bold':        ['0.875rem',{ lineHeight: '1.25rem',  letterSpacing: '0.01em',  fontWeight: '700' }],
        'caption':           ['0.75rem', { lineHeight: '1rem',     fontWeight: '500' }],
      },
      animation: {
        'float': 'float 6s ease-in-out infinite',
      },
      keyframes: {
        float: {
          '0%, 100%': { transform: 'translateY(0px)' },
          '50%':      { transform: 'translateY(-12px)' },
        },
      },
    },
  },
  plugins: [],
}
